qualcomm-cdi-generator.py: add missing comma after merge conflict resolution
The manual merge conflict resolution missed a comma, add it in.

Fixes:
```python
  File "/root/qualcomm-CDI-generator/./qualcomm-cdi-generator.py", line 158
    "mounts" : list(filter(None, mountentries))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

Signed-off-by: Koen Kooi <koen.kooi@oss.qualcomm.com>